#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("startup.Resource", IsApplication=true)]

namespace startup
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f04000d
			public const int SignInButton = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int SignUpButton = 2130968590;
			
			// aapt resource value: 0x7f040009
			public const int Uaudio = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int Uimage = 2130968586;
			
			// aapt resource value: 0x7f040007
			public const int Updf = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int Uppt = 2130968584;
			
			// aapt resource value: 0x7f04000c
			public const int button1 = 2130968588;
			
			// aapt resource value: 0x7f040018
			public const int button2 = 2130968600;
			
			// aapt resource value: 0x7f040020
			public const int confirm = 2130968608;
			
			// aapt resource value: 0x7f04001d
			public const int course = 2130968605;
			
			// aapt resource value: 0x7f04000f
			public const int display = 2130968591;
			
			// aapt resource value: 0x7f040023
			public const int domain = 2130968611;
			
			// aapt resource value: 0x7f040006
			public const int editText1 = 2130968582;
			
			// aapt resource value: 0x7f040019
			public const int email = 2130968601;
			
			// aapt resource value: 0x7f040012
			public const int email_address = 2130968594;
			
			// aapt resource value: 0x7f040001
			public const int imageView1 = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int imageView2 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int imageView3 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int imageView4 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int imageView5 = 2130968581;
			
			// aapt resource value: 0x7f040011
			public const int linearLayout1 = 2130968593;
			
			// aapt resource value: 0x7f040017
			public const int login = 2130968599;
			
			// aapt resource value: 0x7f04001e
			public const int major = 2130968606;
			
			// aapt resource value: 0x7f04001c
			public const int mobile = 2130968604;
			
			// aapt resource value: 0x7f04001a
			public const int name = 2130968602;
			
			// aapt resource value: 0x7f04001f
			public const int password = 2130968607;
			
			// aapt resource value: 0x7f040013
			public const int password_text = 2130968595;
			
			// aapt resource value: 0x7f040015
			public const int radioButton1 = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int radioButton2 = 2130968598;
			
			// aapt resource value: 0x7f040014
			public const int radioGroup1 = 2130968596;
			
			// aapt resource value: 0x7f040000
			public const int relativeLayout1 = 2130968576;
			
			// aapt resource value: 0x7f040024
			public const int signup = 2130968612;
			
			// aapt resource value: 0x7f040021
			public const int student = 2130968609;
			
			// aapt resource value: 0x7f04001b
			public const int surname = 2130968603;
			
			// aapt resource value: 0x7f040022
			public const int teacher = 2130968610;
			
			// aapt resource value: 0x7f04000b
			public const int textView1 = 2130968587;
			
			// aapt resource value: 0x7f040010
			public const int textview = 2130968592;
			
			// aapt resource value: 0x7f040025
			public const int welcomeVideo = 2130968613;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int AboutUs = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Answerpage = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Dashboard = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Home = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Main = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Search = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int SignIn = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int SignUp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Welcome = 2130837512;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
